In [149]:
import pandas as pd
from hurdat2 import load_hurdat2, add_derived_columns

#cargar hurdat
population_df = pd.read_csv(r"C:\Users\espeo\OneDrive\Escritorio\vientovis\vientovis\vientovis\data\population\co-est2024-alldata.csv", encoding='cp1252')
hurdat2_df, hurricanes = load_hurdat2(r"C:\Users\espeo\OneDrive\Escritorio\vientovis\vientovis\vientovis\notebooks\hurricanes\hurdat2-1851-2025-091226.txt")
hurdat2_df = add_derived_columns(hurdat2_df)

hurdat2_df[(hurdat2_df["storm_name"] == "KATRINA") & (hurdat2_df["date"].str.contains("2005"))]

,storm_id,storm_name,date,time,record_id,status,lat,lon,wind_kt,pressure_mb,...,r50_sw,r50_nw,r64_ne,r64_se,r64_sw,r64_nw,datetime,category,is_landfall,coast_approach
44598,AL122005,KATRINA,20050823,1800,,TD,23.1,-75.1,30,1008.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-23 18:00:00,TD,False,False
44599,AL122005,KATRINA,20050824,0000,,TD,23.4,-75.7,30,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-24 00:00:00,TD,False,False
44600,AL122005,KATRINA,20050824,0600,,TD,23.8,-76.2,30,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-24 06:00:00,TD,False,False
44601,AL122005,KATRINA,20050824,1200,,TS,24.5,-76.5,35,1006.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-24 12:00:00,TS,False,False
44602,AL122005,KATRINA,20050824,1800,,TS,25.4,-76.9,40,1003.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-24 18:00:00,TS,False,False
44603,AL122005,KATRINA,20050825,0000,,TS,26.0,-77.7,45,1000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-25 00:00:00,TS,False,False
44604,AL122005,KATRINA,20050825,0600,,TS,26.1,-78.4,50,997.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-25 06:00:00,TS,False,False
44605,AL122005,KATRINA,20050825,1200,,TS,26.2,-79.0,55,994.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-25 12:00:00,TS,False,False
44606,AL122005,KATRINA,20050825,1800,,TS,26.2,-79.6,60,988.0,...,20.0,20.0,0.0,0.0,0.0,0.0,2005-08-25 18:00:00,TS,False,False
44607,AL122005,KATRINA,20050825,2230,L,HU,26.0,-80.1,70,984.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2005-08-25 22:30:00,Cat 1,True,False
44608,AL122005,KATRINA,20050826,0000,,HU,25.9,-80.3,70,983.0,...,20.0,20.0,10.0,10.0,10.0,10.0,2005-08-26 00:00:00,Cat 1,False,False
44609,AL122005,KATRINA,20050826,0600,,HU,25.4,-81.3,65,987.0,...,20.0,20.0,10.0,10.0,10.0,10.0,2005-08-26 06:00:00,Cat 1,False,False
44610,AL122005,KATRINA,20050826,1200,,HU,25.1,-82.0,75,979.0,...,25.0,20.0,20.0,20.0,10.0,10.0,2005-08-26 12:00:00,Cat 1,False,False
44611,AL122005,KATRINA,20050826,1800,,HU,24.9,-82.6,85,968.0,...,35.0,20.0,20.0,20.0,15.0,10.0,2005-08-26 18:00:00,Cat 2,False,False
44612,AL122005,KATRINA,20050827,0000,,HU,24.6,-83.3,90,959.0,...,40.0,30.0,25.0,25.0,20.0,15.0,2005-08-27 00:00:00,Cat 2,False,False
44613,AL122005,KATRINA,20050827,0600,,HU,24.4,-84.0,95,950.0,...,45.0,60.0,35.0,30.0,30.0,25.0,2005-08-27 06:00:00,Cat 2,False,False
44614,AL122005,KATRINA,20050827,1200,,HU,24.4,-84.7,100,942.0,...,45.0,60.0,35.0,30.0,30.0,25.0,2005-08-27 12:00:00,Cat 3,False,False
44615,AL122005,KATRINA,20050827,1800,,HU,24.5,-85.3,100,948.0,...,60.0,70.0,45.0,35.0,35.0,35.0,2005-08-27 18:00:00,Cat 3,False,False
44616,AL122005,KATRINA,20050828,0000,,HU,24.8,-85.9,100,941.0,...,65.0,80.0,60.0,45.0,45.0,50.0,2005-08-28 00:00:00,Cat 3,False,False
44617,AL122005,KATRINA,20050828,0600,,HU,25.2,-86.7,125,930.0,...,75.0,100.0,75.0,75.0,50.0,75.0,2005-08-28 06:00:00,Cat 4,False,False
44618,AL122005,KATRINA,20050828,1200,,HU,25.7,-87.7,145,909.0,...,75.0,100.0,90.0,90.0,50.0,75.0,2005-08-28 12:00:00,Cat 5,False,False
44619,AL122005,KATRINA,20050828,1800,,HU,26.3,-88.6,150,902.0,...,75.0,120.0,90.0,90.0,50.0,90.0,2005-08-28 18:00:00,Cat 5,False,False
44620,AL122005,KATRINA,20050829,0000,,HU,27.2,-89.2,140,905.0,...,75.0,100.0,90.0,90.0,60.0,80.0,2005-08-29 00:00:00,Cat 5,False,False
44621,AL122005,KATRINA,20050829,0600,,HU,28.2,-89.6,125,913.0,...,75.0,100.0,90.0,90.0,60.0,70.0,2005-08-29 06:00:00,Cat 4,False,False
44622,AL122005,KATRINA,20050829,1110,L,HU,29.3,-89.6,110,920.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2005-08-29 11:10:00,Cat 3,True,False
44623,AL122005,KATRINA,20050829,1200,,HU,29.5,-89.6,110,923.0,...,75.0,75.0,90.0,90.0,60.0,60.0,2005-08-29 12:00:00,Cat 3,False,False
44624,AL122005,KATRINA,20050829,1445,L,HU,30.2,-89.6,105,928.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2005-08-29 14:45:00,Cat 3,True,False
44625,AL122005,KATRINA,20050829,1800,,HU,31.1,-89.6,80,948.0,...,75.0,75.0,50.0,50.0,30.0,30.0,2005-08-29 18:00:00,Cat 1,False,False
44626,AL122005,KATRINA,20050830,0000,,TS,32.6,-89.1,50,961.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-30 00:00:00,TS,False,False
44627,AL122005,KATRINA,20050830,0600,,TS,34.1,-88.6,40,978.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-30 06:00:00,TS,False,False
44628,AL122005,KATRINA,20050830,1200,,TD,35.6,-88.0,30,985.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-30 12:00:00,TD,False,False
44629,AL122005,KATRINA,20050830,1800,,TD,37.0,-87.0,30,990.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-30 18:00:00,TD,False,False
44630,AL122005,KATRINA,20050831,0000,,EX,38.6,-85.3,30,994.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-31 00:00:00,TD,False,False
44631,AL122005,KATRINA,20050831,0600,,EX,40.1,-82.9,25,996.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2005-08-31 06:00:00,TD,False,False

In [150]:
Impactos = pd.read_csv(r"C:\Users\espeo\OneDrive\Escritorio\vientovis\vientovis\vientovis\data\impacts\storm_events_daily.csv")
Dano = pd.read_csv (r"C:\Users\espeo\OneDrive\Escritorio\vientovis\vientovis\vientovis\data\damage\nfip_daily_damage.csv")
Cantidad = pd.read_csv (r"C:\Users\espeo\OneDrive\Escritorio\vientovis\vientovis\vientovis\data\damage\nfip_storm_totals.csv")

In [151]:
# formato yy-mm-dd, cantidad solo tiene el año
hurdat2_df["datetime"] = pd.to_datetime(hurdat2_df["datetime"]).dt.strftime(
    "%y-%m-%d")


Impactos["date"] = pd.to_datetime(
    Impactos["date"], format="mixed", errors="coerce"
).dt.strftime("%y-%m-%d")

Dano["date"] = pd.to_datetime(
    Dano["date"], format="mixed", errors="coerce"
).dt.strftime("%y-%m-%d")

In [152]:
# Cortar año de columna storm df daño 
Dano["storm"] = (Dano["storm"].str.replace(r"\s*\d{4}", "", regex=True).str.strip().str.upper())
Impactos["storm"] = (Impactos["storm"].str.replace(r"\s*\d{4}", "", regex=True).str.strip().str.upper())
Cantidad["storm"] = Cantidad["storm"].astype(str).str.strip()
Cantidad["datetime"] = Cantidad["storm"].str.extract(r"(\d{4})")
Cantidad["storm"] = (Cantidad["storm"].str.replace(r"\d{4}", "", regex=True).str.strip().str.upper())
Cantidad

,storm,api_count,records_pulled,building_damage_usd,contents_damage_usd,complete,datetime
0,KATRINA,210576,210576,1.539753e+10,4.808957e+09,yes,2005
1,IKE,52914,52914,2.231230e+09,6.461611e+08,yes,2008
2,SANDY,142555,142555,7.867841e+09,1.140438e+09,yes,2012
3,HARVEY,91772,91772,7.073627e+09,2.444166e+09,yes,2017
4,IRMA,33437,33437,9.815288e+08,1.963622e+08,yes,2017
5,MARIA,898,898,3.372242e+07,1.063654e+07,yes,2017
6,MICHAEL,4400,4400,2.095127e+08,4.386703e+07,yes,2018
7,IDA,27589,27589,1.135003e+09,3.835971e+08,yes,2021
8,IAN,48503,48503,4.333275e+09,8.580647e+08,yes,2022
9,HELENE,58059,58059,6.204399e+09,1.006015e+09,yes,2024

In [153]:
hurdat2_df.rename(columns={"storm_name": "storm"}, inplace=True)
Impactos.rename(columns={"date": "datetime"}, inplace=True)
Dano.rename(columns={"date": "datetime"}, inplace=True)

In [154]:
# Concatenar Impactos a hurdat2_df

impactos_resumen = Impactos.groupby(
    ["storm", "datetime"], as_index=False
).first()
dano_resumen = Dano.groupby(["storm", "datetime"], as_index=False).first()

# storm y datetime
cols_impactos = [
    col
    for col in impactos_resumen.columns
    if col not in ["storm", "datetime"] and col not in hurdat2_df.columns
]
cols_dano = [
    col
    for col in dano_resumen.columns
    if col not in ["storm", "datetime"]
    and col not in hurdat2_df.columns
    and col not in cols_impactos
]

# Unimos con hurdat
hurdat2_df = hurdat2_df.merge(
    impactos_resumen[["storm", "datetime"] + cols_impactos],
    on=["storm", "datetime"],
    how="left",
)

hurdat2_df = hurdat2_df.merge(
    dano_resumen[["storm", "datetime"] + cols_dano],
    on=["storm", "datetime"],
    how="left",
)


hurdat2_df[(hurdat2_df["storm"] == "KATRINA") & (hurdat2_df["date"].str.contains("2005"))]

,storm_id,storm,date,time,record_id,status,lat,lon,wind_kt,pressure_mb,...,deaths_direct,deaths_indirect,injuries_direct,injuries_indirect,damage_property_usd,damage_crops_usd,states,claims,building_damage_usd,contents_damage_usd
44598,AL122005,KATRINA,20050823,1800,,TD,23.1,-75.1,30,1008.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44599,AL122005,KATRINA,20050824,0000,,TD,23.4,-75.7,30,1007.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44600,AL122005,KATRINA,20050824,0600,,TD,23.8,-76.2,30,1007.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44601,AL122005,KATRINA,20050824,1200,,TS,24.5,-76.5,35,1006.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44602,AL122005,KATRINA,20050824,1800,,TS,25.4,-76.9,40,1003.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44603,AL122005,KATRINA,20050825,0000,,TS,26.0,-77.7,45,1000.0,...,6.0,0.0,0.0,0.0,1.000000e+08,4.230000e+08,FLORIDA,5863.0,8.363901e+07,2.713114e+07
44604,AL122005,KATRINA,20050825,0600,,TS,26.1,-78.4,50,997.0,...,6.0,0.0,0.0,0.0,1.000000e+08,4.230000e+08,FLORIDA,5863.0,8.363901e+07,2.713114e+07
44605,AL122005,KATRINA,20050825,1200,,TS,26.2,-79.0,55,994.0,...,6.0,0.0,0.0,0.0,1.000000e+08,4.230000e+08,FLORIDA,5863.0,8.363901e+07,2.713114e+07
44606,AL122005,KATRINA,20050825,1800,,TS,26.2,-79.6,60,988.0,...,6.0,0.0,0.0,0.0,1.000000e+08,4.230000e+08,FLORIDA,5863.0,8.363901e+07,2.713114e+07
44607,AL122005,KATRINA,20050825,2230,L,HU,26.0,-80.1,70,984.0,...,6.0,0.0,0.0,0.0,1.000000e+08,4.230000e+08,FLORIDA,5863.0,8.363901e+07,2.713114e+07
44608,AL122005,KATRINA,20050826,0000,,HU,25.9,-80.3,70,983.0,...,0.0,0.0,0.0,0.0,6.900000e+06,0.000000e+00,FLORIDA,1936.0,2.595488e+07,8.438429e+06
44609,AL122005,KATRINA,20050826,0600,,HU,25.4,-81.3,65,987.0,...,0.0,0.0,0.0,0.0,6.900000e+06,0.000000e+00,FLORIDA,1936.0,2.595488e+07,8.438429e+06
44610,AL122005,KATRINA,20050826,1200,,HU,25.1,-82.0,75,979.0,...,0.0,0.0,0.0,0.0,6.900000e+06,0.000000e+00,FLORIDA,1936.0,2.595488e+07,8.438429e+06
44611,AL122005,KATRINA,20050826,1800,,HU,24.9,-82.6,85,968.0,...,0.0,0.0,0.0,0.0,6.900000e+06,0.000000e+00,FLORIDA,1936.0,2.595488e+07,8.438429e+06
44612,AL122005,KATRINA,20050827,0000,,HU,24.6,-83.3,90,959.0,...,0.0,0.0,0.0,0.0,1.350000e+09,0.000000e+00,ALABAMA|ATLANTIC NORTH|FLORIDA|GULF OF MEXICO|...,192.0,5.544396e+06,1.595841e+06
44613,AL122005,KATRINA,20050827,0600,,HU,24.4,-84.0,95,950.0,...,0.0,0.0,0.0,0.0,1.350000e+09,0.000000e+00,ALABAMA|ATLANTIC NORTH|FLORIDA|GULF OF MEXICO|...,192.0,5.544396e+06,1.595841e+06
44614,AL122005,KATRINA,20050827,1200,,HU,24.4,-84.7,100,942.0,...,0.0,0.0,0.0,0.0,1.350000e+09,0.000000e+00,ALABAMA|ATLANTIC NORTH|FLORIDA|GULF OF MEXICO|...,192.0,5.544396e+06,1.595841e+06
44615,AL122005,KATRINA,20050827,1800,,HU,24.5,-85.3,100,948.0,...,0.0,0.0,0.0,0.0,1.350000e+09,0.000000e+00,ALABAMA|ATLANTIC NORTH|FLORIDA|GULF OF MEXICO|...,192.0,5.544396e+06,1.595841e+06
44616,AL122005,KATRINA,20050828,0000,,HU,24.8,-85.9,100,941.0,...,982.0,0.0,0.0,0.0,2.427852e+10,5.000000e+03,ALABAMA|FLORIDA|IOWA|LOUISIANA|MISSISSIPPI,9112.0,4.597580e+08,1.591025e+08
44617,AL122005,KATRINA,20050828,0600,,HU,25.2,-86.7,125,930.0,...,982.0,0.0,0.0,0.0,2.427852e+10,5.000000e+03,ALABAMA|FLORIDA|IOWA|LOUISIANA|MISSISSIPPI,9112.0,4.597580e+08,1.591025e+08
44618,AL122005,KATRINA,20050828,1200,,HU,25.7,-87.7,145,909.0,...,982.0,0.0,0.0,0.0,2.427852e+10,5.000000e+03,ALABAMA|FLORIDA|IOWA|LOUISIANA|MISSISSIPPI,9112.0,4.597580e+08,1.591025e+08
44619,AL122005,KATRINA,20050828,1800,,HU,26.3,-88.6,150,902.0,...,982.0,0.0,0.0,0.0,2.427852e+10,5.000000e+03,ALABAMA|FLORIDA|IOWA|LOUISIANA|MISSISSIPPI,9112.0,4.597580e+08,1.591025e+08
44620,AL122005,KATRINA,20050829,0000,,HU,27.2,-89.2,140,905.0,...,16.0,0.0,115.0,0.0,5.932022e+09,1.506015e+09,ALABAMA|ARKANSAS|FLORIDA|GEORGIA|KENTUCKY|LOUI...,183970.0,1.411080e+10,4.356870e+09
44621,AL122005,KATRINA,20050829,0600,,HU,28.2,-89.6,125,913.0,...,16.0,0.0,115.0,0.0,5.932022e+09,1.506015e+09,ALABAMA|ARKANSAS|FLORIDA|GEORGIA|KENTUCKY|LOUI...,183970.0,1.411080e+10,4.356870e+09
44622,AL122005,KATRINA,20050829,1110,L,HU,29.3,-89.6,110,920.0,...,16.0,0.0,115.0,0.0,5.932022e+09,1.506015e+09,ALABAMA|ARKANSAS|FLORIDA|GEORGIA|KENTUCKY|LOUI...,183970.0,1.411080e+10,4.356870e+09
44623,AL122005,KATRINA,20050829,1200,,HU,29.5,-89.6,110,923.0,...,16.0,0.0,115.0,0.0,5.932022e+09,1.506015e+09,ALABAMA|ARKANSAS|FLORIDA|GEORGIA|KENTUCKY|LOUI...,183970.0,1.411080e+10,4.356870e+09
44624,AL122005,KATRINA,20050829,1445,L,HU,30.2,-89.6,105,928.0,...,16.0,0.0,115.0,0.0,5.932022e+09,1.506015e+09,ALABAMA|ARKANSAS|FLORIDA|GEORGIA|KENTUCKY|LOUI...,183970.0,1.411080e+10,4.356870e+09
44625,AL122005,KATRINA,20050829,1800,,HU,31.1,-89.6,80,948.0,...,16.0,0.0,115.0,0.0,5.932022e+09,1.506015e+09,ALABAMA|ARKANSAS|FLORIDA|GEORGIA|KENTUCKY|LOUI...,183970.0,1.411080e+10,4.356870e+09
44626,AL122005,KATRINA,20050830,0000,,TS,32.6,-89.1,50,961.0,...,0.0,0.0,0.0,0.0,1.796000e+06,0.000000e+00,GEORGIA|ILLINOIS|INDIANA|KENTUCKY|MAINE|MISSIS...,6039.0,4.625148e+08,1.636140e+08
44627,AL122005,KATRINA,20050830,0600,,TS,34.1,-88.6,40,978.0,...,0.0,0.0,0.0,0.0,1.796000e+06,0.000000e+00,GEORGIA|ILLINOIS|INDIANA|KENTUCKY|MAINE|MISSIS...,6039.0,4.625148e+08,1.636140e+08
44628,AL122005,KATRINA,20050830,1200,,TD,35.6,-88.0,30,985.0,...,0.0,0.0,0.0,0.0,1.796000e+06,0.000000e+00,GEORGIA|ILLINOIS|INDIANA|KENTUCKY|MAINE|MISSIS...,6039.0,4.625148e+08,1.636140e+08
44629,AL122005,KATRINA,20050830,1800,,TD,37.0,-87.0,30,990.0,...,0.0,0.0,0.0,0.0,1.796000e+06,0.000000e+00,GEORGIA|ILLINOIS|INDIANA|KENTUCKY|MAINE|MISSIS...,6039.0,4.625148e+08,1.636140e+08
44630,AL122005,KATRINA,20050831,0000,,EX,38.6,-85.3,30,994.0,...,0.0,0.0,0.0,0.0,1.850000e+05,0.000000e+00,KENTUCKY|MAINE|MASSACHUSETTS|PENNSYLVANIA|RHOD...,3229.0,2.382039e+08,8.806831e+07
44631,AL122005,KATRINA,20050831,0600,,EX,40.1,-82.9,25,996.0,...,0.0,0.0,0.0,0.0,1.850000e+05,0.000000e+00,KENTUCKY|MAINE|MASSACHUSETTS|PENNSYLVANIA|RHOD...,3229.0,2.382039e+08,8.806831e+07

In [155]:
# Sacamos el año de date de hurdat 
hurdat2_df["datetime_year"] = hurdat2_df["date"].astype(str).str[:4]

Cantidad["datetime"] = Cantidad["datetime"].astype(str).str.strip()
Cantidad["storm"] = Cantidad["storm"].astype(str).str.strip().str.upper()
#dejamos todas las columnas mismo nombre
cantidad_renombrado = Cantidad.rename(
    columns={
        "datetime": "year_storm",
        "building_damage_usd": "total_building_damage_usd",
        "contents_damage_usd": "total_contents_damage_usd",
        "api_count": "total_api_count",
        "records_pulled": "total_records_pulled",
        "complete": "total_complete",
    }
)

hurdat2_df = hurdat2_df.merge(
    cantidad_renombrado,
    left_on=["storm", "datetime_year"],
    right_on=["storm", "year_storm"],
    how="inner",
).drop(columns=["datetime_year", "year_storm"])

hurdat2_df

hurdat2_df

,storm_id,storm,date,time,record_id,status,lat,lon,wind_kt,pressure_mb,...,damage_crops_usd,states,claims,building_damage_usd,contents_damage_usd,total_api_count,total_records_pulled,total_building_damage_usd,total_contents_damage_usd,total_complete
0,AL122005,KATRINA,20050823,1800,,TD,23.1,-75.1,30,1008.0,...,NaN,NaN,NaN,NaN,NaN,210576,210576,1.539753e+10,4.808957e+09,yes
1,AL122005,KATRINA,20050824,0000,,TD,23.4,-75.7,30,1007.0,...,NaN,NaN,NaN,NaN,NaN,210576,210576,1.539753e+10,4.808957e+09,yes
2,AL122005,KATRINA,20050824,0600,,TD,23.8,-76.2,30,1007.0,...,NaN,NaN,NaN,NaN,NaN,210576,210576,1.539753e+10,4.808957e+09,yes
3,AL122005,KATRINA,20050824,1200,,TS,24.5,-76.5,35,1006.0,...,NaN,NaN,NaN,NaN,NaN,210576,210576,1.539753e+10,4.808957e+09,yes
4,AL122005,KATRINA,20050824,1800,,TS,25.4,-76.9,40,1003.0,...,NaN,NaN,NaN,NaN,NaN,210576,210576,1.539753e+10,4.808957e+09,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,AL092024,HELENE,20240927,1800,,LO,36.8,-84.9,40,983.0,...,329818200.0,ALABAMA|ATLANTIC SOUTH|FLORIDA|GEORGIA|ILLINOI...,11730.0,1.269544e+09,198536413.0,58059,58059,6.204399e+09,1.006015e+09,yes
488,AL092024,HELENE,20240928,0000,,LO,38.1,-86.6,40,985.0,...,0.0,NORTH CAROLINA|TENNESSEE,569.0,4.270692e+07,7914776.0,58059,58059,6.204399e+09,1.006015e+09,yes
489,AL092024,HELENE,20240928,0600,,LO,37.4,-88.1,30,992.0,...,0.0,NORTH CAROLINA|TENNESSEE,569.0,4.270692e+07,7914776.0,58059,58059,6.204399e+09,1.006015e+09,yes
490,AL092024,HELENE,20240928,1200,,LO,36.6,-87.6,25,997.0,...,0.0,NORTH CAROLINA|TENNESSEE,569.0,4.270692e+07,7914776.0,58059,58059,6.204399e+09,1.006015e+09,yes
491,AL092024,HELENE,20240928,1800,,LO,37.1,-87.0,20,1000.0,...,0.0,NORTH CAROLINA|TENNESSEE,569.0,4.270692e+07,7914776.0,58059,58059,6.204399e+09,1.006015e+09,yes

In [156]:
#exportar a json hurdat2_df
hurdat2_df.to_json("hurricanes.json", orient="records", indent=4, date_format="iso")